{% set name = "ampform-dpd" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ampform_dpd-{{ version }}.tar.gz
  sha256: 315edf17a75edb4b1972342b0e445f1b7d1f77ac9cf35093e1ec315c8f1f1364

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python >=3.8
    - ampform >=0.14.8
    - attrs >=20.1.0
    - cloudpickle
    - jax
    - jaxlib
    - qrules >=0.10.0
    - sympy >=1.10
    - tensorwaves

test:
  imports:
    - ampform_dpd
  commands:
    - pip check
  requires:
    - pip

about:
  dev_url: https://github.com/ComPWA/ampform-dpd
  doc_url: https://compwa.github.io/ampform-dpd
  home: https://github.com/ComPWA/ampform-dpd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Symbolic expressions for amplitude model building with Dalitz-Plot Decomposition

extra:
  recipe-maintainers:
    - redeboer
    - shenvitor
