{% set name = "ampform-dpd" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 5f3b39045e95d9805876d78e1298b386552b2f7acc470605c2aa8a3b292c62f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python >=3.8
    - ampform >=0.14.8
    - attrs >=20.1.0
    - cloudpickle
    - jax
    - jaxlib
    - sympy >=1.10
    - tensorwaves

test:
  imports:
    - ampform_dpd
  commands:
    - pip check
  requires:
    - pip

about:
  dev_url: https://github.com/ComPWA/ampform-dpd
  doc_url: https://compwa.github.io/ampform-dpd
  home: https://github.com/ComPWA/ampform-dpd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Symbolic expressions for Dalitz-Plot Decomposition

extra:
  recipe-maintainers:
    - redeboer
    - shenvitor
