{% set name = "ampform-dpd" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 8964dce19e9fe239e855913203a7ca84a2fa93932a05cd2f65e78d42e961df45

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=36.2.1
    - setuptools-scm
  run:
    - python >=3.7
    - ampform >=0.14.4,<0.15.dev0
    - attrs >=20.1.0
    - cloudpickle
    - jax
    - jaxlib
    - sympy >=1.10
    - tensorwaves
    - typing-extensions

test:
  imports:
    - ampform_dpd
  commands:
    - pip check
  requires:
    - pip

about:
  dev_url: https://github.com/ComPWA/ampform-dpd
  doc_url: https://compwa.github.io/ampform-dpd
  home: https://github.com/ComPWA/ampform-dpd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Symbolic expressions for Dalitz-Plot Decomposition

extra:
  recipe-maintainers:
    - redeboer
    - shenvitor
