{% set name = "ampform-dpd" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ampform_dpd-{{ version }}.tar.gz
  sha256: 2cfcd67b98e342ad051b6e2c2ccc3c97f3c145792cc62c36373e230611c3edc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - ampform >=0.15.7
    - attrs >=20.1.0
    - cloudpickle
    - frozendict
    - jax
    - jaxlib
    - numpy
    - qrules >=0.10.0
    - sympy >=1.10
    - tensorwaves
    - typing-extensions

test:
  imports:
    - ampform_dpd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  dev_url: https://github.com/ComPWA/ampform-dpd
  doc_url: https://ampform-dpd.readthedocs.io
  home: https://github.com/ComPWA/ampform-dpd
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Symbolic expressions for amplitude model building with Dalitz-Plot Decomposition

extra:
  recipe-maintainers:
    - redeboer
    - shenvitor
